"""add advisor request csv path

Revision ID: 038d6fa5625b
Revises: c833c1a104da
Create Date: 2026-04-06 13:18:11.080619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038d6fa5625b'
down_revision = 'c833c1a104da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisor_student_list_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('csv_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisor_student_list_requests', schema=None) as batch_op:
        batch_op.drop_column('csv_path')

    # ### end Alembic commands ###
