"""increase password_hash column size to 255

Revision ID: 495bca582ebc
Revises: d845776bc3a3
Create Date: 2026-08-15 18:55:14.066142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495bca582ebc'
down_revision = 'd845776bc3a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
