"""Add attendance assignment test exam to Result

Revision ID: 72241a6b04b3
Revises: 
Create Date: 2026-04-03 17:50:51.754019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72241a6b04b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('assignment', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('test', sa.Float(), nullable=False))
        batch_op.drop_column('ca')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ca', sa.FLOAT(), nullable=False))
        batch_op.drop_column('test')
        batch_op.drop_column('assignment')
        batch_op.drop_column('attendance')

    # ### end Alembic commands ###
